language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
script:
  - pytest test_app.py
  - pytest test_integration.py
  - pytest test_texter.py
  - pycodestyle *.py
notifications:
  email: false